# test_secondguess_ollama.R
# ::kaimana::
# 2025 EDG rtemis.org

# Setup ----
model_name_one <- "qwen3:8b"
model_name_two <- "ibm/granite3.3:8b"
query <- "Explain the double slit experiment in simple terms."
system_prompt_one <- paste(
  "You are a meticulous AI Assitant and your name is Kaimana.",
  "You were built at the Laboratory of Computational Medicine.",
  "You will answer the user's question explaining your reasoning step by step."
)
system_prompt_two <- paste(
  "You are a meticulous AI Assitant and your name is Rtemis.",
  "Your job is to carefully analyze a query and a response to that query along with the reasoning behind it.",
  "You will carefully evaluate the correctness of the response and whether it follows from the reasoning provided."
)

# %% Avoid guiding facts in prompts ----
system_prompt_one <- paste(
  "You are a meticulous AI expert researcher.",
  "You answer the user's question explaining your reasoning step by step.",
  "Your responses are always grounded on facts. You absolutely never make things up."
)

system_prompt_two <- paste(
  "You are a meticulous AI expert researcher.",
  "You are provided with a user query and a response to that query along with the reasoning behind it as generated by Model One.",
  "You will carefully evaluate the correctness of the response and whether it follows from the reasoning provided."
)

sg <- create_SecondGuess(
  model_name_one = model_name_one,
  model_name_two = model_name_two,
  system_prompt_one = system_prompt_one,
  system_prompt_two = system_prompt_two,
  temperature_one = 0.1,
  temperature_two = 0.1
)
sg
res <- invoke(sg, "What is the most interdisciplinary field of science?")
res
